name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true

    - name: Install dependencies
      run: bundle install

    - name: Build site
      run: bundle exec jekyll build -d docs/_site # Assegure que o local está correto

    - name: Archive artifact
      run: |
        mkdir -p docs/_site
        tar -cvf site.tar docs/_site

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_site
